# TODO: Move to pyproject.toml once ready
target-version = "py39"
line-length = 79
extend-exclude = [
  "cupy/array_api",
  "docs/source",
  "tests/cupy_tests/array_api_tests",
  "third_party",
]

[lint]
select = ["E", "F", "W", "UP"]

[lint.per-file-ignores]
"cupyx/scipy/special/_gammainc.py" = [
  "E501", # line-too-long (table of constants)
]
"tests/typing_tests/cupy_tests/creation_tests/test_basic.pyi" = [
  "E501", # line-too-long (long comments)
]
