language: python

cache:
  - pip
  - ccache

python:
  - "2.7"
  - "3.4"
  - "3.5"

install:
  - pip install -U pip wheel
  - pip install cython
  - python setup.py sdist --cupy-no-cuda
  - pip install autopep8 hacking

script:
  - flake8 --config=.flake8.cython
  - autopep8 -r . --global-config .pep8 --diff | tee check_autopep8
  - test ! -s check_autopep8
  - READTHEDOCS=True python setup.py develop

sudo: false
