name: "Backport"

on:
  pull_request_target:
    types: [closed, labeled]
    branches:
       - master

jobs:
  backport:
    if: |
        github.repository_owner == 'cupy' &&
        github.event.pull_request.merged == true &&
        contains(github.event.pull_request.labels.*.name, 'to-be-backported')
    runs-on: ubuntu-18.04
    env:
      CUPY_CI: GitHub

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    - name: setup backport
      run: |
        pip install pygithub
        git config --global user.name "CuPy Automatic Backport"
        git config --global user.email "33715081+chainer-ci@users.noreply.github.com"
        git clone https://github.com/cupy/backport.git

    - name: run_backport
      env:
        BACKPORT_GITHUB_TOKEN: ${{secrets.BACKPORT_TOKEN}}
      run: |
        cd backport
        echo -e "machine github.com\nlogin chainer-ci\npassword ${{secrets.BACKPORT_TOKEN}}" > ~/.netrc
        python backport.py --repo cupy --pr ${{github.event.number}} --https
