name: Docker

on:
  release:
    types: [published]
  pull_request:
    paths:
      - docker/**
      - .github/workflows/docker.yml

jobs:
  docker-build-push:
    if: |
        github.repository_owner == 'cupy' ||
        github.event_name != 'release'
    runs-on: ubuntu-latest
    env:
      DOCKER_TAG_NAME: ${{ (github.event_name == 'release' && github.event.release.tag_name) || 'pull-request-test' }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to DockerHub
      if: github.event_name == 'release'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Docker Build & Push (docker/python3)
      uses: docker/build-push-action@v2
      with:
        context: docker/python3
        tags: cupy/cupy:${{ env.DOCKER_TAG_NAME }}
        push: ${{ github.event_name == 'release' }}

    - name: Docker Build & Push (docker/rocm)
      uses: docker/build-push-action@v2
      with:
        context: docker/rocm
        tags: cupy/cupy-rocm:${{ env.DOCKER_TAG_NAME }}
        push: ${{ github.event_name == 'release' }}
