name: "Pull-Request Update"

on:
  issue_comment:
  pull_request:
    types: [edited, synchronize, converted_to_draft, ready_for_review, review_requested, auto_merge_disabled]
  pull_request_review:
  pull_request_review_comment:

jobs:
  mark-needs-attention:
    if: |
      github.repository_owner == 'cupy' &&
      (
        (
            github.event_name == 'issue_comment' &&
            github.event.issue.state == 'open' &&
            github.event.issue.pull_request &&
            !contains(github.event.issue.assignees.*.login, github.actor)
        ) ||
        (
            github.event_name != 'issue_comment' &&
            github.event.pull_request.state == 'open' &&
            !contains(github.event.pull_request.assignees.*.login, github.actor)
        )
      )
    runs-on: ubuntu-22.04
    steps:
      - name: Needs Attention
        run: |
          echo "The pull-request will be marked as Needs Attention from maintainers."
          echo "${{ (github.event.pull_request || github.event.issue).number }}" > PULL_REQUEST_NUMBER
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: PULL_REQUEST_NUMBER
          path: PULL_REQUEST_NUMBER
